export const menuItems = [
  { value: 'home', label: 'Home', path: '/' },
  { value: 'basic', label: 'Basic', path: '/basic' },
  { value: 'read-only', label: 'Read Only', path: '/read-only' },
  { value: 'locale', label: 'Locale', path: '/locale' },
  { value: 'views', label: 'Views', path: '/views' },
  { value: 'custom-header', label: 'Custom Header', path: '/custom-header' },
  { value: 'custom-event-style', label: 'Custom Event Style', path: '/custom-event-style' },
  { value: 'add-resource', label: 'Add Resource', path: '/add-resource' },
  { value: 'drag-and-drop', label: 'Drag and Drop', path: '/drag-and-drop' },
  { value: 'summary', label: 'Summary', path: '/summary' },
  { value: 'add-more', label: 'Add More', path: '/add-more' },
  { value: 'overlap-check', label: 'Overlap Check', path: '/overlap-check' },
  { value: 'no-cross-slot-move', label: 'No cross-slot move', path: '/no-cross-slot-move' },
  { value: 'freeze-first-row', label: 'Freeze First Row', path: '/freeze-first-row' },
  { value: 'resource-clickable', label: 'Resource clickable', path: '/resource-clickable' },
  { value: 'custom-table-headers', label: 'Custom table headers', path: '/custom-table-headers' },
  { value: 'hide-weekends', label: 'Hide weekends', path: '/hide-weekends' },
  { value: 'custom-time-window', label: 'Custom time window', path: '/custom-time-window' },
  { value: 'infinite-scroll', label: 'Infinite scroll', path: '/infinite-scroll' },
  { value: 'infinite-scroll-2', label: 'Infinite scroll 2', path: '/infinite-scroll-2' },
  { value: 'custom-popover-style', label: 'Custom popover style', path: '/custom-popover-style' },
];
